[package]
name = "phili/anm"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
t = "osyrisrblx/t@^1.3.0"
roact = "roblox/roact@^1.4.4"
rodux = "roblox/rodux@^3.0.0"
roact-rodux = "roblox/roact-rodux@^0.2.2"
flipper = "reselim/flipper@^1.1.1"
promise = "evaera/promise@^4.0.0"
net = "ffrostflame/net@^1.0.3"
janitor = "howmanysmall/janitor@^1.15.4"
matter = "matter-ecs/matter@^0.8.0"
cmdr = "evaera/cmdr@^1.12.0"
tableutil = "stravant/tableutil@^1.2.7"
llama = "freddylist/llama@^1.0.3"
collections = "centau/collections@^1.0.5"
signal = "sleitnick/signal@^1.5.0"
maid = "quenty/maid@^2.0.0"
bridgenet2 = "ffrostflame/bridgenet2@^2.0.0"
fastcast = "etithespirit/fastcast@^1.1.0"
partcache = "etithespirit/partcache@^1.2.0"
smartbone = "pseduocoreh/smartbone@^1.0.0"
boattween = "reggiejnr/boattween@^1.0.0"
